### ISSUE TITLE
waiting for supporting EXT_X_DISCONTINUITY_SEQUENCE

### ISSUE THREAD

**Issue by HiroyukTamura** [carlanton/m3u8-parser#16]
Thank you for your hard work.

I want to handle `EXT_X_DISCONTINUITY_SEQUENCE` in my project.
I know you're working on unsupported tags and refactoring. 
Is there any work to contribute to this project?
I'll take on if you give me a task.

**Comment by carlanton** [comment]
Thank you! :-)
I've just released version 0.12 with support for that tag to maven. It should be available in an hour or so.

I think that all tags from RFC 8216 are supported since 0.12. If you find something that is missing or if you have ideas of how to improve other things, pull requests and issues are always welcome!

**Comment by HiroyukTamura** [comment]
Ok I see, thank you for your speedy release.
